# Generated by Django 4.0.6 on 2024-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
