# Generated by Django 4.0.6 on 2024-04-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_projeto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='conceitos_aplicados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='github_repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias_usadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
