# Generated by Django 4.0.6 on 2024-04-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_projeto_conceitos_aplicados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='area_cientifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.areacientifica'),
        ),
    ]
