# Generated by Django 4.0.6 on 2024-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
