# Generated by Django 4.0.6 on 2024-03-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_alter_classificacao_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='classificacao_media',
        ),
    ]
