# Generated by Django 4.0.6 on 2024-03-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_remove_artigo_classificacao_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='classificacao_media',
            field=models.FloatField(default=0),
        ),
    ]
