# Generated by Django 4.0.6 on 2024-04-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_artigo_classificacao_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artigos.classificacao'),
        ),
    ]
